<?php

/**
 * BlogPostTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogPostTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlogPostTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BlogPostTag');
    }
}