<?php

/**
 * VmtestAffiliateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VmtestAffiliateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VmtestAffiliateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VmtestAffiliate');
    }
}