<?php

/**
 * VmtestCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VmtestCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VmtestCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VmtestCategory');
    }
}