<?php

/**
 * VmtestJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VmtestJobTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VmtestJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VmtestJob');
    }
}