<?php

/**
 * BaseVmtestCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $VmtestJobs
 * @property Doctrine_Collection $VmtestAffiliates
 * @property Doctrine_Collection $VmtestCategoryAffiliate
 * 
 * @method string              getName()                    Returns the current record's "name" value
 * @method Doctrine_Collection getVmtestJobs()              Returns the current record's "VmtestJobs" collection
 * @method Doctrine_Collection getVmtestAffiliates()        Returns the current record's "VmtestAffiliates" collection
 * @method Doctrine_Collection getVmtestCategoryAffiliate() Returns the current record's "VmtestCategoryAffiliate" collection
 * @method VmtestCategory      setName()                    Sets the current record's "name" value
 * @method VmtestCategory      setVmtestJobs()              Sets the current record's "VmtestJobs" collection
 * @method VmtestCategory      setVmtestAffiliates()        Sets the current record's "VmtestAffiliates" collection
 * @method VmtestCategory      setVmtestCategoryAffiliate() Sets the current record's "VmtestCategoryAffiliate" collection
 * 
 * @package    vmtest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVmtestCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vmtest_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('VmtestJob as VmtestJobs', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('VmtestAffiliate as VmtestAffiliates', array(
             'refClass' => 'VmtestCategoryAffiliate',
             'local' => 'category_id',
             'foreign' => 'affiliate_id'));

        $this->hasMany('VmtestCategoryAffiliate', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}