<?php

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $BlogPosts
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method Doctrine_Collection getBlogPosts() Returns the current record's "BlogPosts" collection
 * @method Tag                 setName()      Sets the current record's "name" value
 * @method Tag                 setBlogPosts() Sets the current record's "BlogPosts" collection
 * 
 * @package    vmtest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BlogPost as BlogPosts', array(
             'refClass' => 'BlogPostTag',
             'local' => 'tag_id',
             'foreign' => 'blog_post_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}