<?php

/**
 * BaseVmtestCategoryAffiliate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $affiliate_id
 * @property VmtestCategory $VmtestCategory
 * @property VmtestAffiliate $VmtestAffiliate
 * 
 * @method integer                 getCategoryId()      Returns the current record's "category_id" value
 * @method integer                 getAffiliateId()     Returns the current record's "affiliate_id" value
 * @method VmtestCategory          getVmtestCategory()  Returns the current record's "VmtestCategory" value
 * @method VmtestAffiliate         getVmtestAffiliate() Returns the current record's "VmtestAffiliate" value
 * @method VmtestCategoryAffiliate setCategoryId()      Sets the current record's "category_id" value
 * @method VmtestCategoryAffiliate setAffiliateId()     Sets the current record's "affiliate_id" value
 * @method VmtestCategoryAffiliate setVmtestCategory()  Sets the current record's "VmtestCategory" value
 * @method VmtestCategoryAffiliate setVmtestAffiliate() Sets the current record's "VmtestAffiliate" value
 * 
 * @package    vmtest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVmtestCategoryAffiliate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vmtest_category_affiliate');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('affiliate_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('VmtestCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('VmtestAffiliate', array(
             'local' => 'affiliate_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}