<?php

/**
 * BaseVmtestAffiliate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $email
 * @property string $token
 * @property boolean $is_active
 * @property Doctrine_Collection $VmtestCategories
 * @property Doctrine_Collection $VmtestCategoryAffiliate
 * 
 * @method string              getUrl()                     Returns the current record's "url" value
 * @method string              getEmail()                   Returns the current record's "email" value
 * @method string              getToken()                   Returns the current record's "token" value
 * @method boolean             getIsActive()                Returns the current record's "is_active" value
 * @method Doctrine_Collection getVmtestCategories()        Returns the current record's "VmtestCategories" collection
 * @method Doctrine_Collection getVmtestCategoryAffiliate() Returns the current record's "VmtestCategoryAffiliate" collection
 * @method VmtestAffiliate     setUrl()                     Sets the current record's "url" value
 * @method VmtestAffiliate     setEmail()                   Sets the current record's "email" value
 * @method VmtestAffiliate     setToken()                   Sets the current record's "token" value
 * @method VmtestAffiliate     setIsActive()                Sets the current record's "is_active" value
 * @method VmtestAffiliate     setVmtestCategories()        Sets the current record's "VmtestCategories" collection
 * @method VmtestAffiliate     setVmtestCategoryAffiliate() Sets the current record's "VmtestCategoryAffiliate" collection
 * 
 * @package    vmtest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVmtestAffiliate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vmtest_affiliate');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('VmtestCategory as VmtestCategories', array(
             'refClass' => 'VmtestCategoryAffiliate',
             'local' => 'affiliate_id',
             'foreign' => 'category_id'));

        $this->hasMany('VmtestCategoryAffiliate', array(
             'local' => 'id',
             'foreign' => 'affiliate_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}