<?php

/**
 * BaseBlogPostTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $blog_post_id
 * @property integer $tag_id
 * 
 * @method integer     getBlogPostId()   Returns the current record's "blog_post_id" value
 * @method integer     getTagId()        Returns the current record's "tag_id" value
 * @method BlogPostTag setBlogPostId()   Sets the current record's "blog_post_id" value
 * @method BlogPostTag setTagId()        Sets the current record's "tag_id" value
 * 
 * @package    vmtest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlogPostTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_post_tag');
        $this->hasColumn('blog_post_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tag_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}