<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/04/02 02:00:37

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=vmtest',
  'username' => 'admin',
  'password' => 'admin',
  'name' => 'doctrine',
)),);
